eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
      - id: service1
        uri: lb://SERVICE1
        predicates:
        - Path=/service1/**
        filters:
        - RewritePath=/service1/(?<path>.*), /$\{path}
      - id: service2
        uri: lb://SERVICE2
        predicates:
        - Path=/service2/**
        filters:
        - RewritePath=/service2/(?<path>.*), /$\{path}
